-- Italia Cosmetics D1 schema
-- Replaces the WooCommerce/WordPress database entirely.

CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY,
  brand TEXT NOT NULL DEFAULT 'Italia Cosmetics',
  name TEXT NOT NULL,
  line TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  price REAL NOT NULL DEFAULT 0,
  orig_price REAL,
  currency TEXT NOT NULL DEFAULT 'PKR',
  cat TEXT NOT NULL DEFAULT 'Product',
  badge TEXT NOT NULL DEFAULT '',
  rating INTEGER NOT NULL DEFAULT 5,
  img TEXT NOT NULL DEFAULT '',
  total_sales INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status TEXT NOT NULL DEFAULT 'processing',
  currency TEXT NOT NULL DEFAULT 'PKR',
  total REAL NOT NULL DEFAULT 0,
  customer_id INTEGER REFERENCES customers(id),
  billing_first_name TEXT NOT NULL DEFAULT '',
  billing_last_name TEXT NOT NULL DEFAULT '',
  billing_email TEXT NOT NULL DEFAULT '',
  billing_phone TEXT NOT NULL DEFAULT '',
  billing_address_1 TEXT NOT NULL DEFAULT '',
  billing_city TEXT NOT NULL DEFAULT '',
  billing_state TEXT NOT NULL DEFAULT '',
  billing_postcode TEXT NOT NULL DEFAULT '',
  billing_country TEXT NOT NULL DEFAULT 'PK',
  payment_method TEXT NOT NULL DEFAULT 'cod',
  payment_method_title TEXT NOT NULL DEFAULT 'Cash on Delivery',
  set_paid INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id),
  name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  price REAL NOT NULL DEFAULT 0,
  total REAL NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

CREATE TABLE IF NOT EXISTS blog_posts (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  author TEXT NOT NULL DEFAULT 'Italia Editorial Board',
  cat TEXT NOT NULL DEFAULT 'Shampoo',
  excerpt TEXT NOT NULL DEFAULT '',
  gradient TEXT NOT NULL DEFAULT 'linear-gradient(135deg,#8B5FBF,#A07DD6)',
  icon TEXT NOT NULL DEFAULT 'fa-star',
  img TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS brands (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  css_id TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  gradient TEXT NOT NULL DEFAULT 'linear-gradient(135deg,#8B5FBF,#A07DD6)',
  description TEXT NOT NULL DEFAULT '',
  text_color TEXT NOT NULL DEFAULT '#fff',
  img TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS testimonials (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT '',
  text TEXT NOT NULL DEFAULT '',
  rating INTEGER NOT NULL DEFAULT 5,
  avatar TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '',
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Single-tenant admin accounts for the dashboard (separate from `customers`,
-- who are storefront shoppers with no dashboard access).
CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_login_at TEXT
);

-- Session tokens are high-entropy (32 random bytes from crypto.getRandomValues)
-- so, unlike passwords, storing them unhashed is standard practice -- they are
-- bearer tokens generated by the system, never chosen or reused by a human.
CREATE TABLE IF NOT EXISTS admin_sessions (
  token TEXT PRIMARY KEY,
  admin_user_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires ON admin_sessions(expires_at);

-- Storefront customer sessions (separate from admin_sessions -- customers
-- never get dashboard access). Same high-entropy-token rationale applies.
CREATE TABLE IF NOT EXISTS customer_sessions (
  token TEXT PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_customer_sessions_expires ON customer_sessions(expires_at);
